Fix crash in res.send()
In commit c6fa25985b078ce0ba27da50d1d8676d3e18fe30, "var" usage
was replaced with const. The code previously worked because "var"
has function scoping unlike const which has block scoping.

TypeError: Cannot read property 'attributes' of null