Fix error from missing tls.createConnection() method:
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object #<Object> has no method 'createConnection'
    at newConnection (/usr/local/lib/node/.npm/ldapjs/0.1.0/package/lib/client.js:142:15)
    at new Client (/usr/local/lib/node/.npm/ldapjs/0.1.0/package/lib/client.js:223:27)
    at Object.createClient (/usr/local/lib/node/.npm/ldapjs/0.1.0/package/lib/index.js:48:12)